name: mood_waves
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    
  url_launcher: ^6.2.5

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  firebase_core: ^2.27.0
  intl: ^0.19.0
  table_calendar: ^3.1.0
  # fl_chart: ^0.66.2
  bubble_tab_indicator: ^0.1.4
  fl_chart: ^0.62.0
  flutter_linkify: ^6.0.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  build_runner: ^2.1.4
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: any

flutter:
  uses-material-design: true
