name: Dart CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        
      - name: Download pub Dependencies
        run: flutter pub get
        
      - name: Run analyzer
        run: flutter analyze
      
 
